name: Docker Build and K8s Manifest Update

on:
  schedule:
    - cron: '40 3 * * *'
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  INFRA_REPO: ysfAskri/hello-world-k8s

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: infra
          fetch-depth: 1

      - name: Debug - Show yaml contents before
        run: |
          echo "Before:"
          cat infra/hello-world.yaml

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|image: ghcr.io/ysfaskri/hello-world-react:.*|image: ghcr.io/ysfaskri/hello-world-react:${{ steps.get_version.outputs.VERSION }}|' infra/hello-world.yaml
          if git -C infra diff --exit-code; then
            echo "No changes to commit"
            echo "CHANGES_EXIST=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "CHANGES_EXIST=true" >> $GITHUB_ENV
          fi

      - name: Debug - Show yaml contents after
        run: |
          echo "After:"
          cat infra/hello-world.yaml

      - name: Commit and push changes
        if: env.CHANGES_EXIST == 'true'
        run: |
          cd infra
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update image to ${{ steps.get_version.outputs.VERSION }}"
          git push

      - name: No changes detected
        if: env.CHANGES_EXIST == 'false'
        run: echo "No changes were made to the infrastructure repository"